version: "3"

services:  
  selenium:
      image: selenium/standalone-chrome:latest
      container_name: selenium-hub
      ports:
        - "4444:4444"
  redis:
    image: redis
  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-python
    ports:
      - "8888:8888"
    volumes:
     - .:/db
    depends_on:
      - redis
      - selenium
    environment: 
      - REDIS_HOST=redis